# Generated by Django 3.0.6 on 2020-05-24 05:13

from django.db import migrations
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuariocustom',
            managers=[
                ('objects', usuarios.models.UsuarioManager()),
            ],
        ),
    ]
