# Generated by Django 3.0.6 on 2020-05-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200524_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocustom',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuariocustom',
            name='cpf',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
